

spring:
    application:
        name:
            edu
    datasource:
        url: jdbc:mysql://localhost:3306/ictedu_db
        username: ictedu
        password: 1111
        driver-class-name: com.mysql.cj.jdbc.Driver

    web:
        resources:
            static-locations: file:D:/upload/
    security:
        oauth2:
            client:
                registration:
                    kakao:
                        client-id: 0900cd5bf1e2db78a54535878be14d68
                        client-secret: EhNEJ2yBFM6bcy9ziYaaR93aUEMjkf7p
                        redirect-uri: http://localhost:8080/login/oauth2/code/kakao
                        authorization-grant-type: authorization_code
                        client-authentication-method: client_secret_post
                        client-name: Kakao
                        scope:
                            - profile_nickname
                            - profile_image
                            - account_email 
                    naver:
                        client-id: 12zOYNteRtOThofIa9za
                        client-secret:  k34skEEj9d
                        redirect-uri: http://localhost:8080/login/oauth2/code/naver
                        authorization-grant-type: authorization_code
                        client-name: Naver
                        scope:
                            - name
                            - email
                provider:
                    kakao:
                        authorization-uri: https://kauth.kakao.com/oauth/authorize
                        token-uri: https://kauth.kakao.com/oauth/token
                        user-info-uri: https://kapi.kakao.com/v2/user/me
                        user-name-attribute: id
                    naver:
                        authorization-uri: https://nid.naver.com/oauth2.0/authorize
                        token-uri: https://nid.naver.com/oauth2.0/token
                        user-info-uri: https://openapi.naver.com/v1/nid/me
                        user-name-attribute: response
                        
file:
    upload-dir: D:/upload

server:
    port: 8080
    servlet:
        context-path: /

mybatis:
    mapper-locations: mapper/*.xml
    type-aliases-package: com.ict.edu3

# 비밀키 사용(32바이트길이)  
# 1 시간 = 1000ms * 60 * 60 ;
jwt:
    secret : "abcdASDF1234abcdQWER0987poiuPOIU"
    expiration : 3600000